[package]
name = "platune"
version = "0.1.0"
authors = ["Austin Schey <aschey13@gmail.com>"]
edition = "2018"
build="build.rs"

[target.'cfg(not(target_os="windows"))'.dependencies]
pnet_datalink = "0.26.0"

[dependencies]
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0.57"
actix-web = "3.0.2"
actix-cors = "0.4.0"
actix-service = "1.0.6"
actix-http = "2.0.0"
actix-rt = "1.1.1"
actix-files = "0.3.0"
actix-server = "1.0.4"
mime_guess = "2.0.3"
subprocess = "0.2.6"
fstrings = "0.2.3"
futures = "0.3.5"
dirs = "3.0.1"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
diesel_migrations = "1.4.0"
paperclip = { git = "https://github.com/wafflespeanut/paperclip", rev = "c3f81f6", features = ["actix"] }
paperclip-actix = { git = "https://github.com/wafflespeanut/paperclip", rev = "c3f81f6" }
dotenv = "0.15.0"
sysinfo = "0.15.2"
itertools = "0.9.0"
failure = "0.1.8"
katatsuki = { git = "https://github.com/aschey/seiri", rev = "169b0b8" }
num_cpus = "1.13.0"
async-std = { version = "1.6.4", features = ["attributes", "tokio02"] }
image = "0.23.10"
color-thief = "0.2.1"
whoami = "0.9.0"
regex = "1.3.9"
anyhow = "1.0.32"
rust-embed = "5.6.0"
