[package]
name = "namp"
version = "0.1.0"
authors = ["Austin Schey <aschey13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(windows)'.dependencies]
web-view = { version = "0.6.2", features = ["edge"] }

[target.'cfg(unix)'.dependencies]
web-view = { version = "0.6.2" }
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
actix-web = "2.0.0"
actix-cors = "0.2.0"
actix-rt = "1.0.0"
actix-files = "0.2.1"
mime_guess = "2.0.1"
subprocess = "0.2.4"
fstrings = "0.2.2"
dirs = "2.0.2"
diesel = { version = "1.4.4", features = ["sqlite"] }
paperclip = { git = "https://github.com/wafflespeanut/paperclip", rev = "e80180f", features = ["actix"] }
dotenv = "0.15.0"