[package]
name = "namp"
version = "0.1.0"
authors = ["Austin Schey <aschey13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.6.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-files = "0.2.1"
mime_guess = "2.0.1"