[package]
name = "namp"
version = "0.1.0"
authors = ["Austin Schey <aschey13@gmail.com>"]
edition = "2018"
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
actix-web = "2.0.0"
actix-cors = "0.2.0"
actix-service = "1.0.5"
actix-http = "1.0.1"
actix-rt = "1.0.0"
actix-files = "0.2.1"
actix-server = "1.0.2"
mime_guess = "2.0.1"
subprocess = "0.2.4"
fstrings = "0.2.2"
futures = "0.3.4"
dirs = "2.0.2"
diesel = { version = "1.4.4", features = ["sqlite"] }
paperclip = { git = "https://github.com/wafflespeanut/paperclip", rev = "e80180f", features = ["actix"] }
dotenv = "0.15.0"
sysinfo = "0.13.1"
itertools = "0.9.0"
failure = "0.1.7"
katatsuki = { path = "../seiri/katatsuki/katatsuki-rs" }
num_cpus = "1.13.0"
async-std = { version = "1.5.0", features = ["attributes"] }
zmq = "0.9.2"