[package]
authors = ["Austin Schey <aschey13@gmail.com>"]
edition = "2018"
name = "libplatune-management"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = {version = "0.5.4", features = ["runtime-tokio-rustls"]}
tokio = "1.6.0"
