[package]
name = "platuned"
version = "0.1.0"
authors = ["aschey <aschey13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="1.2", features=["full"]}
flexi_logger = "0.17.1"
yansi = "0.5.0"
libplatune-player = {path = "../../libplatune/player", features=["runtime-tokio"]}
log = "0.4.14"
tonic = { git = "https://github.com/hyperium/tonic", rev="61555ff" }
tonic-reflection = { git = "https://github.com/hyperium/tonic", rev="61555ff" }
prost = "0.7.0"
tokio-stream = {version = "0.1.3", features=["net"] }
futures = "0.3.13"

[build-dependencies]
tonic-build = { git = "https://github.com/grippy/tonic", rev="da029464", features=["prost"] }

