[package]
authors = ["aschey <aschey13@gmail.com>"]
edition = "2018"
name = "platuned"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexi_logger = "0.17.1"
futures = "0.3.13"
libplatune-player = {path = "../../libplatune/player", features = ["runtime-tokio"]}
log = "0.4.14"
prost = "0.7.0"
tokio = {version = "1.2", features = ["full"]}
tokio-stream = {version = "0.1.3", features = ["net"]}
tonic = {git = "https://github.com/hyperium/tonic", rev = "61555ff"}
tonic-reflection = {git = "https://github.com/hyperium/tonic", rev = "61555ff"}
yansi = "0.5.0"

[build-dependencies]
tonic-build = {git = "https://github.com/grippy/tonic", rev = "da029464", features = ["prost"]}
