[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2018"

[lib]

name = "libplatune_player"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["runtime-tokio"]
runtime-async-std = ["async-std"]
runtime-tokio = ["tokio"]

[dependencies]
async-std = {version = "1.9.0", optional = true, features = ["unstable"]}
log = "0.4.14"
postage = "0.4.1"
rodio = {git = "https://github.com/aschey/rodio", rev = "0ddb286"}
strum_macros = "0.20.1"
tokio = {version = "1.6.0", optional = true, features = ["rt"]}

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.50"
ctor = "0.1.19"
flexi_logger = "0.17.1"
futures = "0.3.15"
rstest = "0.6.4"
yansi = "0.5.0"
