[package]
authors = ["aschey <aschey13@gmail.com>"]
name = "libplatune-player"
version = "0.1.0"

edition = "2018"

[lib]
name = "libplatune_player"
path = "src/lib.rs"

[features]
default = ["runtime-tokio"]
dummy = ["rodio/dummy"]
runtime-tokio = ["tokio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
futures-util = "0.3.15"
log = "0.4.14"
postage = "0.4.1"
reqwest = {version = "0.11.3", features = ["stream"]}
rodio = {git = "https://github.com/aschey/rodio", rev = "bc38e3d"}
strum_macros = "0.20.1"
tokio = {version = "1.6.0", features = ["full"], optional = true}

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.50"
ctor = "0.1.19"
flexi_logger = "0.17.1"
futures = "0.3.15"
rstest = "0.10.0"
tokio = {version = "1.6.0", features = ["full"]}
yansi = "0.5.0"
