on: [push]

name: CI

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: docker build . -t libplatune-test && docker run --rm libplatune-test
